### ISSUE TITLE
Duplicate Block not updating unique IDs when first published

### ISSUE THREAD

**Issue by diggeddy** [kadencewp/kadence-blocks#65]
Raised Issue with Gutenberg - bug since 6.5 update:
https://github.com/WordPress/gutenberg/issues/17536

**Comment by HardeepAsrani** [comment]
I'll just drop by to say it's not really an issue with Gutenberg but how the plugin is assigning IDs. We had the similar issue at first in https://wordpress.org/plugins/otter-blocks/

We just added this condition to make sure the ID used & clientId of the block is same when block is added. If it exists but isn't the same, which happens when block is duplicated, then to update it.

```
if ( props.attributes.id === undefined || props.attributes.id.substr( id.length - 8 ) !== props.clientId.substr( 0, 8 ) ) {
	const instanceId = `wp-block-themeisle-blocks-button-group-${ props.clientId.substr( 0, 8 ) }`;
	props.setAttributes({ id: instanceId });
}
```

Hope it helps. Keep the awesome work up with Kadence blocks. :)

**Comment by talldan** [comment]
Just adding a note that I've closed the related issue in Gutenberg. I think this is something that needs to be investigated in the plugin first. If any assistance is needed, feel free to point me to the code that generates the IDs and I can look into it.

If it's discovered that a fix needs to be applied in Gutenberg I can help with that too.

**Comment by kadencewp** [comment]
Thanks for posting about this. There is a system in to prevent this already. It seems that since 6.5 this.props.setAttributes isn't running under componentDidMount when a block is duplicated. I'm looking to see if I can find out why. @talldan if you have any guesses I would love to hear?

 And thanks @HardeepAsrani for the post and code. The reason I didn't go that route (started there) is it forces an ID change every time you open the post because the client id isn't static. It meant that the post "updated" every time you looked at the editor even if you didn't make any changes.

**Comment by kadencewp** [comment]
@diggeddy I pushed out an update, let me know if that solves it for you.

Ben

**Comment by diggeddy** [comment]
Just tested it - working perfectly. What was the issue?

**Comment by kadencewp** [comment]
Well didn't make any sense, for some reason setAttributes wasn't sticking, but by applying the new id to the attribute object it worked. I'm still trying to make sense of why that would be needed. Or what changed in Gutenberg to cause that.

**Comment by diggeddy** [comment]
Not the first thing Gut does that doesn't make sense. Thanks for letting us know.

**Comment by talldan** [comment]
@kadencewp Would you be able to point to the code in the plugin that handled this and the change that fixed it? I'll see if I can debug the issue. Thanks.

**Comment by kadencewp** [comment]
@talldan This line all I added: https://github.com/kadencewp/kadence-blocks/blob/master/src/blocks/row-layout/edit.js#L120

Ben
