### ISSUE TITLE
Block validation error in multisite installation

### ISSUE THREAD

**Issue by staude** [kadencewp/kadence-blocks#82]
On a WordPress 5.3.2 multisite we have the following problem. 

Users with user roles smaller than (Super)Admin can save the button block, but a selected icon does not appear on the output page.

Here the colleague has made a video of this.
https://youtu.be/jYj3n2Ir4Fg

If the user wants to edit the post again, an error message "This block contains unexpected or invalid content" appears

<img width="806" alt="2020-02-04_1555" src="https://user-images.githubusercontent.com/870951/73755769-d12f5d80-4766-11ea-879d-f2f72ad99397.png">

This message is in the browser console.

<img width="1130" alt="2020-02-04_1533" src="https://user-images.githubusercontent.com/870951/73755667-a9d89080-4766-11ea-95e8-7f1cd5915a97.png">

It appears ONLY in the multisite, tested with WordPress 5.3.2 with and without Gutenberg plugin

**Comment by kadencewp** [comment]
Hey,
 Inside of a multisite environment, even admin users are not allowed to post html like svgs. With Gutenberg, I've been expecting core to address this because the filters they run through content that is posted prevents a lot of content that is normal for the web today.

My suggestion is to use this plugin: https://wordpress.org/plugins/unfiltered-mu/

Or if you want to just be specific with our blocks this plugin I created will just work out the button issues with the core filter.
http://download.kadencethemes.com/kadence-blocks-author-svg-support.zip

Ben

**Comment by staude** [comment]
Thank you for pointing out the plugins. I tested them and they work. Is there already a core ticket in the WordPress Trac for  it?

**Comment by kadencewp** [comment]
I've seen several some that want to add support for SVG, some that want to add an option to enable SVG support some that just want extra filters in place so SVG can be more easily supported. For example right now even if you add in filters to allow svg in kses it breaks for svgs that use line tags because line tags have x1, y1, etc attributes, and all attributes are filtered in kses get numbers removed which breaks the line tags and currently there is not even a filter in place to prevent that. 

Another issue you have in kses is that is doesn't support RGBA color for inline styles. 

Lots of SVG talk here: https://core.trac.wordpress.org/ticket/24251

https://tracsearch.wpteamhub.com/?search=%22kses+svg%22

With Gutenberg allowing you to create all kinds of content then saving it as static html we now have tons of html going through the kses filter that would have traditionally just been metadata then the html created for output through php and thus never ran through the kses filter so the whole thing needs some rethought in my opinion.

**Comment by staude** [comment]
Thanks a lot for the links. 
For the time being there is nothing to do but wait and see, so I close the ticket.
